tap "homebrew/cask"
tap "mongodb/brew"

# brew install
brew "bat"
brew "git"
brew "git-delta"
brew "fzf"
brew "chezmoi"
brew "watch"
brew "jq"
brew "yq"
brew "tmux-xpanes"
brew "dive"
brew "helm"
brew "k9s"
brew "kubectl"
brew "kubectx"
brew "awscli"
brew "ghz"
brew "nvm"
brew "mongodb-community"

brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"

# brew install --cask
cask "iterm2"
cask "hammerspoon"
cask "sublime-text"
cask "lens"
cask "kap"
cask "visualvm"
cask "zoom"
cask "visual-studio-code"
cask "docker"
cask "mongodb-compass"
cask "robo-3t"
cask "dbeaver-community"
cask "charles"
cask "todoist"
cask "deepl"
cask "raycast"
